# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'mathqt.ui'
##
## Created by: Qt User Interface Compiler version 6.8.3
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QLabel, QLineEdit, QMainWindow,
    QPushButton, QSizePolicy, QSpinBox, QStatusBar,
    QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1726, 777)
        self.actionDownload_PDF = QAction(MainWindow)
        self.actionDownload_PDF.setObjectName(u"actionDownload_PDF")
        self.actionDownload_PDF_2 = QAction(MainWindow)
        self.actionDownload_PDF_2.setObjectName(u"actionDownload_PDF_2")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.lineEdit = QLineEdit(self.centralwidget)
        self.lineEdit.setObjectName(u"lineEdit")
        self.lineEdit.setGeometry(QRect(10, 30, 291, 31))
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(10, 10, 91, 16))
        self.pushButton = QPushButton(self.centralwidget)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(10, 130, 291, 23))
        self.widget = QWidget(self.centralwidget)
        self.widget.setObjectName(u"widget")
        self.widget.setGeometry(QRect(320, 30, 681, 341))
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.label_5 = QLabel(self.centralwidget)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(590, 380, 141, 16))
        self.label_6 = QLabel(self.centralwidget)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(1290, 380, 141, 16))
        self.label_8 = QLabel(self.centralwidget)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(590, 10, 131, 16))
        self.pushButton_2 = QPushButton(self.centralwidget)
        self.pushButton_2.setObjectName(u"pushButton_2")
        self.pushButton_2.setGeometry(QRect(40, 160, 75, 23))
        self.pushButton_3 = QPushButton(self.centralwidget)
        self.pushButton_3.setObjectName(u"pushButton_3")
        self.pushButton_3.setGeometry(QRect(120, 160, 75, 23))
        self.pushButton_4 = QPushButton(self.centralwidget)
        self.pushButton_4.setObjectName(u"pushButton_4")
        self.pushButton_4.setGeometry(QRect(200, 160, 75, 23))
        self.lineEdit_5 = QLineEdit(self.centralwidget)
        self.lineEdit_5.setObjectName(u"lineEdit_5")
        self.lineEdit_5.setGeometry(QRect(20, 90, 131, 31))
        self.lineEdit_5.setReadOnly(False)
        self.lineEdit_6 = QLineEdit(self.centralwidget)
        self.lineEdit_6.setObjectName(u"lineEdit_6")
        self.lineEdit_6.setGeometry(QRect(160, 90, 131, 31))
        self.lineEdit_6.setReadOnly(False)
        self.pushButton_5 = QPushButton(self.centralwidget)
        self.pushButton_5.setObjectName(u"pushButton_5")
        self.pushButton_5.setGeometry(QRect(40, 220, 75, 23))
        self.pushButton_6 = QPushButton(self.centralwidget)
        self.pushButton_6.setObjectName(u"pushButton_6")
        self.pushButton_6.setGeometry(QRect(120, 220, 75, 23))
        self.pushButton_7 = QPushButton(self.centralwidget)
        self.pushButton_7.setObjectName(u"pushButton_7")
        self.pushButton_7.setGeometry(QRect(40, 190, 75, 23))
        self.pushButton_8 = QPushButton(self.centralwidget)
        self.pushButton_8.setObjectName(u"pushButton_8")
        self.pushButton_8.setGeometry(QRect(120, 190, 75, 23))
        self.pushButton_9 = QPushButton(self.centralwidget)
        self.pushButton_9.setObjectName(u"pushButton_9")
        self.pushButton_9.setGeometry(QRect(200, 220, 75, 23))
        self.pushButton_10 = QPushButton(self.centralwidget)
        self.pushButton_10.setObjectName(u"pushButton_10")
        self.pushButton_10.setGeometry(QRect(200, 190, 75, 23))
        self.pushButton_11 = QPushButton(self.centralwidget)
        self.pushButton_11.setObjectName(u"pushButton_11")
        self.pushButton_11.setGeometry(QRect(80, 280, 75, 23))
        self.pushButton_12 = QPushButton(self.centralwidget)
        self.pushButton_12.setObjectName(u"pushButton_12")
        self.pushButton_12.setGeometry(QRect(120, 250, 75, 23))
        self.pushButton_13 = QPushButton(self.centralwidget)
        self.pushButton_13.setObjectName(u"pushButton_13")
        self.pushButton_13.setGeometry(QRect(200, 250, 75, 23))
        self.pushButton_14 = QPushButton(self.centralwidget)
        self.pushButton_14.setObjectName(u"pushButton_14")
        self.pushButton_14.setGeometry(QRect(40, 250, 75, 23))
        self.lineEdit_3 = QLineEdit(self.centralwidget)
        self.lineEdit_3.setObjectName(u"lineEdit_3")
        self.lineEdit_3.setGeometry(QRect(20, 430, 291, 31))
        self.lineEdit_3.setReadOnly(True)
        self.lineEdit_4 = QLineEdit(self.centralwidget)
        self.lineEdit_4.setObjectName(u"lineEdit_4")
        self.lineEdit_4.setGeometry(QRect(20, 490, 291, 31))
        self.lineEdit_4.setReadOnly(True)
        self.label_9 = QLabel(self.centralwidget)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(20, 70, 91, 16))
        self.label_4 = QLabel(self.centralwidget)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(20, 470, 91, 16))
        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(20, 350, 71, 16))
        self.label_3 = QLabel(self.centralwidget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(20, 410, 91, 16))
        self.lineEdit_2 = QLineEdit(self.centralwidget)
        self.lineEdit_2.setObjectName(u"lineEdit_2")
        self.lineEdit_2.setGeometry(QRect(20, 370, 291, 31))
        self.lineEdit_2.setReadOnly(True)
        self.label_10 = QLabel(self.centralwidget)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(160, 70, 91, 16))
        self.label_11 = QLabel(self.centralwidget)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setEnabled(True)
        self.label_11.setGeometry(QRect(20, 310, 71, 16))
        font = QFont()
        font.setPointSize(9)
        self.label_11.setFont(font)
        self.pushButton_15 = QPushButton(self.centralwidget)
        self.pushButton_15.setObjectName(u"pushButton_15")
        self.pushButton_15.setGeometry(QRect(170, 280, 75, 23))
        self.spinBox_derivative_order = QSpinBox(self.centralwidget)
        self.spinBox_derivative_order.setObjectName(u"spinBox_derivative_order")
        self.spinBox_derivative_order.setGeometry(QRect(90, 340, 91, 22))
        self.spinBox_derivative_order.setValue(1)
        self.label_12 = QLabel(self.centralwidget)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(1310, 10, 131, 16))
        self.widget_2 = QWidget(self.centralwidget)
        self.widget_2.setObjectName(u"widget_2")
        self.widget_2.setGeometry(QRect(1020, 30, 681, 341))
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_3 = QWidget(self.centralwidget)
        self.widget_3.setObjectName(u"widget_3")
        self.widget_3.setGeometry(QRect(320, 400, 681, 341))
        sizePolicy.setHeightForWidth(self.widget_3.sizePolicy().hasHeightForWidth())
        self.widget_3.setSizePolicy(sizePolicy)
        self.widget_4 = QWidget(self.centralwidget)
        self.widget_4.setObjectName(u"widget_4")
        self.widget_4.setGeometry(QRect(1020, 400, 681, 341))
        sizePolicy.setHeightForWidth(self.widget_4.sizePolicy().hasHeightForWidth())
        self.widget_4.setSizePolicy(sizePolicy)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.actionDownload_PDF.setText(QCoreApplication.translate("MainWindow", u"Download PDF", None))
        self.actionDownload_PDF_2.setText(QCoreApplication.translate("MainWindow", u"Download PDF", None))
        self.lineEdit.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Input Function Here", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Input Function", None))
        self.pushButton.setText(QCoreApplication.translate("MainWindow", u"Calculate", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"Definite Integral Graph", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"Indefinite Integral Graph", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"Original Function Graph", None))
        self.pushButton_2.setText(QCoreApplication.translate("MainWindow", u"a^2", None))
        self.pushButton_3.setText(QCoreApplication.translate("MainWindow", u"a^b", None))
        self.pushButton_4.setText(QCoreApplication.translate("MainWindow", u"sqrt{ }", None))
        self.lineEdit_5.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Upper Bound", None))
        self.lineEdit_6.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Lower Bound", None))
        self.pushButton_5.setText(QCoreApplication.translate("MainWindow", u"(", None))
        self.pushButton_6.setText(QCoreApplication.translate("MainWindow", u")", None))
        self.pushButton_7.setText(QCoreApplication.translate("MainWindow", u"+", None))
        self.pushButton_8.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.pushButton_9.setText(QCoreApplication.translate("MainWindow", u"\u00f7", None))
        self.pushButton_10.setText(QCoreApplication.translate("MainWindow", u"x", None))
        self.pushButton_11.setText(QCoreApplication.translate("MainWindow", u"tan", None))
        self.pushButton_12.setText(QCoreApplication.translate("MainWindow", u"sin", None))
        self.pushButton_13.setText(QCoreApplication.translate("MainWindow", u"cos", None))
        self.pushButton_14.setText(QCoreApplication.translate("MainWindow", u"log", None))
        self.lineEdit_3.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Indefinite Integral Results", None))
        self.lineEdit_4.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Definite Integral Results", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"Upper Bound", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Definite Integral", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Derivative", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Indefinite Integral", None))
        self.lineEdit_2.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Derivative Results", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"Lower Bound", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"RESULTS", None))
        self.pushButton_15.setText(QCoreApplication.translate("MainWindow", u"e^a", None))
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"Derivative Graph", None))
    # retranslateUi

