# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'mathqt.ui'
##
## Created by: Qt User Interface Compiler version 6.8.3
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QLabel, QLineEdit, QMainWindow,
    QPushButton, QSizePolicy, QStatusBar, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1417, 592)
        self.actionDownload_PDF = QAction(MainWindow)
        self.actionDownload_PDF.setObjectName(u"actionDownload_PDF")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.lineEdit = QLineEdit(self.centralwidget)
        self.lineEdit.setObjectName(u"lineEdit")
        self.lineEdit.setGeometry(QRect(10, 30, 291, 31))
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(10, 10, 91, 16))
        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(10, 100, 71, 16))
        self.label_3 = QLabel(self.centralwidget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(10, 160, 91, 16))
        self.label_4 = QLabel(self.centralwidget)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(10, 220, 91, 16))
        self.lineEdit_2 = QLineEdit(self.centralwidget)
        self.lineEdit_2.setObjectName(u"lineEdit_2")
        self.lineEdit_2.setGeometry(QRect(10, 120, 291, 31))
        self.lineEdit_2.setReadOnly(True)
        self.lineEdit_3 = QLineEdit(self.centralwidget)
        self.lineEdit_3.setObjectName(u"lineEdit_3")
        self.lineEdit_3.setGeometry(QRect(10, 180, 291, 31))
        self.lineEdit_3.setReadOnly(True)
        self.lineEdit_4 = QLineEdit(self.centralwidget)
        self.lineEdit_4.setObjectName(u"lineEdit_4")
        self.lineEdit_4.setGeometry(QRect(10, 240, 291, 31))
        self.lineEdit_4.setReadOnly(True)
        self.pushButton = QPushButton(self.centralwidget)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(10, 70, 291, 23))
        self.widget = QWidget(self.centralwidget)
        self.widget.setObjectName(u"widget")
        self.widget.setGeometry(QRect(320, 30, 531, 251))
        self.widget_2 = QWidget(self.centralwidget)
        self.widget_2.setObjectName(u"widget_2")
        self.widget_2.setGeometry(QRect(870, 30, 531, 251))
        self.widget_3 = QWidget(self.centralwidget)
        self.widget_3.setObjectName(u"widget_3")
        self.widget_3.setGeometry(QRect(320, 310, 531, 251))
        self.widget_4 = QWidget(self.centralwidget)
        self.widget_4.setObjectName(u"widget_4")
        self.widget_4.setGeometry(QRect(870, 310, 531, 251))
        self.label_5 = QLabel(self.centralwidget)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(320, 290, 141, 16))
        self.label_6 = QLabel(self.centralwidget)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(870, 290, 141, 16))
        self.label_7 = QLabel(self.centralwidget)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(870, 10, 111, 16))
        self.label_8 = QLabel(self.centralwidget)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(320, 10, 131, 16))
        self.pushButton_2 = QPushButton(self.centralwidget)
        self.pushButton_2.setObjectName(u"pushButton_2")
        self.pushButton_2.setGeometry(QRect(40, 380, 75, 23))
        self.pushButton_3 = QPushButton(self.centralwidget)
        self.pushButton_3.setObjectName(u"pushButton_3")
        self.pushButton_3.setGeometry(QRect(120, 380, 75, 23))
        self.pushButton_4 = QPushButton(self.centralwidget)
        self.pushButton_4.setObjectName(u"pushButton_4")
        self.pushButton_4.setGeometry(QRect(200, 380, 75, 23))
        self.label_9 = QLabel(self.centralwidget)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(10, 280, 91, 16))
        self.label_10 = QLabel(self.centralwidget)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(150, 280, 91, 16))
        self.lineEdit_5 = QLineEdit(self.centralwidget)
        self.lineEdit_5.setObjectName(u"lineEdit_5")
        self.lineEdit_5.setGeometry(QRect(10, 300, 131, 31))
        self.lineEdit_5.setReadOnly(False)
        self.lineEdit_6 = QLineEdit(self.centralwidget)
        self.lineEdit_6.setObjectName(u"lineEdit_6")
        self.lineEdit_6.setGeometry(QRect(150, 300, 131, 31))
        self.lineEdit_6.setReadOnly(False)
        self.pushButton_5 = QPushButton(self.centralwidget)
        self.pushButton_5.setObjectName(u"pushButton_5")
        self.pushButton_5.setGeometry(QRect(80, 420, 75, 23))
        self.pushButton_6 = QPushButton(self.centralwidget)
        self.pushButton_6.setObjectName(u"pushButton_6")
        self.pushButton_6.setGeometry(QRect(160, 420, 75, 23))
        self.pushButton_7 = QPushButton(self.centralwidget)
        self.pushButton_7.setObjectName(u"pushButton_7")
        self.pushButton_7.setGeometry(QRect(80, 450, 75, 23))
        self.pushButton_8 = QPushButton(self.centralwidget)
        self.pushButton_8.setObjectName(u"pushButton_8")
        self.pushButton_8.setGeometry(QRect(160, 450, 75, 23))
        self.pushButton_9 = QPushButton(self.centralwidget)
        self.pushButton_9.setObjectName(u"pushButton_9")
        self.pushButton_9.setGeometry(QRect(80, 480, 75, 23))
        self.pushButton_10 = QPushButton(self.centralwidget)
        self.pushButton_10.setObjectName(u"pushButton_10")
        self.pushButton_10.setGeometry(QRect(160, 480, 75, 23))
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.actionDownload_PDF.setText(QCoreApplication.translate("MainWindow", u"Download PDF", None))
        self.lineEdit.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Input Function Here", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Input Function", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Derivative", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Symbolic Integral", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Numeric Integral", None))
        self.lineEdit_2.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Derivative Results", None))
        self.lineEdit_3.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Symbolic Integral Results", None))
        self.lineEdit_4.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Numeric Integral Results", None))
        self.pushButton.setText(QCoreApplication.translate("MainWindow", u"Submit", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"Symbolic Integral Graph", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"Numeric Integral Graph", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"Derivative Graph", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"Original Function Graph", None))
        self.pushButton_2.setText(QCoreApplication.translate("MainWindow", u"a^2", None))
        self.pushButton_3.setText(QCoreApplication.translate("MainWindow", u"a^b", None))
        self.pushButton_4.setText(QCoreApplication.translate("MainWindow", u"sqrt{ }", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"Higher Bound", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"Lower Bound", None))
        self.lineEdit_5.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Higher Bound", None))
        self.lineEdit_6.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Lower Bound", None))
        self.pushButton_5.setText(QCoreApplication.translate("MainWindow", u"(", None))
        self.pushButton_6.setText(QCoreApplication.translate("MainWindow", u")", None))
        self.pushButton_7.setText(QCoreApplication.translate("MainWindow", u"+", None))
        self.pushButton_8.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.pushButton_9.setText(QCoreApplication.translate("MainWindow", u"/", None))
        self.pushButton_10.setText(QCoreApplication.translate("MainWindow", u"x", None))
    # retranslateUi

